Csharp
kirill-andreyev/c_sharp_tasks pull request #2
Opened 2021-09-23 21:20 UTC by kirill-andreyev

2021-09-23 21:38 UTC, dandreyew requested changes

2021-09-23 21:38 UTC, dandreyew commented on C_SHARP_8115/8115_fixed/8115_fixed/Date.cs
> +        private void StringToDate(string date)
Such methods are usually called Parse

2021-09-23 21:38 UTC, dandreyew commented on C_SHARP_8115/8115_fixed/8115_fixed/Date.cs
> +            month = (date[3] - 48) * 10 + (date[4] - 48);
WHAAAT THE FUCK...

2021-09-23 21:38 UTC, dandreyew commented on C_SHARP_8115/8115_fixed/8115_fixed/Date.cs
> +            month = (date[3] - 48) * 10 + (date[4] - 48);
Holy balls...

2021-09-23 21:38 UTC, dandreyew commented on C_SHARP_8115/8115_fixed/8115_fixed/Date.cs
> +					if (year % 4 == 0)
That's not how it works actually, use google.com

2021-09-23 21:38 UTC, dandreyew commented on C_SHARP_8115/8115_fixed/8115_fixed/Date.cs
> +			switch (month)
1. We have a lamda construction for switch in C# which

2021-09-23 21:38 UTC, dandreyew commented on C_SHARP_8115/8115_fixed/8115_fixed/Date.cs
> +			switch (month)
2. Dictionnary is better

2021-09-23 21:38 UTC, dandreyew commented on C_SHARP_8115/8115_fixed/8115_fixed/Date.cs
> +			Console.WriteLine("How many days you want to add? ");
Why the fuck Date class handles console AGAIN???

2021-09-23 21:45 UTC, lALTAIRl commented on C_SHARP_8115/8115_fixed/8115_fixed/Date.cs
> +					if (year % 4 == 0)
You need to choose one of 3 cases, not 1 of 12.

2021-09-23 21:52 UTC, lALTAIRl requested changes

2021-09-23 21:52 UTC, lALTAIRl commented on C_SHARP_8115/8115_fixed/8115_fixed/Date.cs
> +        private void StringToDate(string date)
Or Convert, anyway method name should contain a verb that discribes an action, that will be done there.

2021-09-23 21:52 UTC, lALTAIRl commented on C_SHARP_8115/8115_fixed/8115_fixed/Date.cs
> +			switch (month)
You need to choose from 3 options, not from 12

2021-09-23 21:52 UTC, lALTAIRl commented on C_SHARP_8115/8115_fixed/8115_fixed/Program.cs
> +                        Console.WriteLine("Wrong choise!");
"Choice" the correct spelling

2021-09-23 21:52 UTC, lALTAIRl commented on C_SHARP_8115/8115_fixed/8115_fixed/Program.cs
> +            switch (choise)
"Choice" again

2021-09-23 21:52 UTC, lALTAIRl commented on C_SHARP_8115/8115_fixed/8115_fixed/Program.cs
> +                        Date date = new Date(year, month, day);
use var for declaring variables

2021-09-23 21:53 UTC, dandreyew commented on C_SHARP_8115/8115_fixed/8115_fixed/Date.cs
> +        private void StringToDate(string date)
> Or Convert, anyway method name should contain a verb that discribes an action, that will be done there.

Convert are usually static members

2021-09-23 21:59 UTC, dandreyew commented on C_SHARP_8115/8115_fixed/8115_fixed/Date.cs
> +            date = DateTime.Now.ToString("dd.MM.yyy");
var date = ...

2021-09-24 07:00 UTC, kirill-andreyev commented on C_SHARP_8115/8115_fixed/8115_fixed/Date.cs
> +					if (year % 4 == 0)
> That's not how it works actually, use google.com

I didn't quite understand what the problem is here

2021-09-24 11:36 UTC, closed without merging

2021-09-24 13:52 UTC, dandreyew commented on C_SHARP_8115/8115_fixed/8115_fixed/Date.cs
> +        private void ParseStringToDate(string date)
just parse. We already know the parameter is string, and we already know the class is Date

2021-09-24 13:52 UTC, dandreyew commented on C_SHARP_8115/8115_fixed/8115_fixed/Date.cs
> +            string[] subDate = date.Split(' ', '.');
use var for local variables

2021-09-24 13:52 UTC, dandreyew commented on C_SHARP_8115/8115_fixed/8115_fixed/Date.cs
> +        public void DisplayDate()
Third time. This class should handle ONLY date. No console should be here.

2021-09-24 13:52 UTC, dandreyew commented on C_SHARP_8115/8115_fixed/8115_fixed/Date.cs
> +		internal void AddDays(int addDay)
What's wrong with the formatting?

2021-09-24 13:52 UTC, dandreyew commented on C_SHARP_8115/8115_fixed/8115_fixed/Date.cs
> +            Dictionary<int, int> monthCount = new(12)
This is a very strange name for the variable

2021-09-24 13:52 UTC, dandreyew commented on C_SHARP_8115/8115_fixed/8115_fixed/Date.cs
> +                else
You don't need else here

2021-09-24 13:52 UTC, dandreyew commented on C_SHARP_8115/8115_fixed/8115_fixed/Date.cs
> +            else
No need in else here

2021-09-24 13:52 UTC, dandreyew commented on C_SHARP_8115/8115_fixed/8115_fixed/Date.cs
> +        public int year;
Place fields and properties before methods

2021-09-24 13:52 UTC, dandreyew commented on C_SHARP_8115/8115_fixed/8115_fixed/Program.cs
> +            Date date;
var date = new Date();